using TraitSharp.SourceGenerator.Models;
using TraitSharp.SourceGenerator.Utilities;

namespace TraitSharp.SourceGenerator.Generators
{
    internal static class ExtensionMethodsGenerator
    {
        public static string Generate(TraitModel trait)
        {
            var builder = new CodeBuilder();
            var contractName = ConstraintInterfaceGenerator.GetContractName(trait);

            builder.AppendLine("// <auto-generated/>");
            builder.AppendLine("#nullable enable");
            builder.AppendLine("using System.Runtime.CompilerServices;");
            builder.AppendLine();
            builder.AppendLine($"namespace {trait.EffectiveNamespace}");
            builder.OpenBrace();

            builder.AppendLine("/// <summary>");
            builder.AppendLine($"/// Extension methods for {trait.Name} trait.");
            builder.AppendLine("/// </summary>");
            builder.AppendLine($"public static class {trait.Name}Extensions");
            builder.OpenBrace();

            // AsLayout method - e.g., AsCoordinate
            // Uses 'this ref T self' to allow zero-copy ref return from caller's storage.
            // C# does not allow 'this in T' on generic extension methods (CS8338),
            // but 'this ref T' is allowed for struct types (C# 7.2+).
            builder.AppendLine("/// <summary>");
            builder.AppendLine("/// Zero-copy cast to layout struct for direct field access.");
            builder.AppendLine("/// </summary>");
            builder.AppendLine("[MethodImpl(MethodImplOptions.AggressiveInlining)]");
            builder.AppendLine($"public static ref readonly {trait.LayoutStructName} As{trait.ShortName}<T>(this ref T self)");
            builder.AppendLine($"    where T : unmanaged, {contractName}<T>");
            builder.OpenBrace();
            builder.AppendLine("return ref T.AsLayout(in self);");
            builder.CloseBrace();
            builder.AppendLine();

            // Individual property accessors
            foreach (var prop in trait.Properties)
            {
                builder.AppendLine("/// <summary>");
                builder.AppendLine($"/// Get {prop.Name} value.");
                builder.AppendLine("/// </summary>");
                builder.AppendLine("[MethodImpl(MethodImplOptions.AggressiveInlining)]");
                builder.AppendLine($"public static {prop.TypeName} Get{prop.Name}<T>(this ref T self)");
                builder.AppendLine($"    where T : unmanaged, {contractName}<T>");
                builder.OpenBrace();
                builder.AppendLine($"return T.Get{prop.Name}_Impl(in self);");
                builder.CloseBrace();
                builder.AppendLine();
            }

            builder.CloseBrace();
            builder.CloseBrace();

            return builder.ToString();
        }
    }
}
