using TraitSharp.SourceGenerator.Models;
using TraitSharp.SourceGenerator.Utilities;

namespace TraitSharp.SourceGenerator.Generators
{
    internal static class LayoutStructGenerator
    {
        public static string Generate(TraitModel trait)
        {
            var builder = new CodeBuilder();

            builder.AppendLine("// <auto-generated/>");
            builder.AppendLine("#nullable enable");
            builder.AppendLine();
            builder.AppendLine($"namespace {trait.EffectiveNamespace}");
            builder.OpenBrace();

            builder.AppendLine("/// <summary>");
            builder.AppendLine($"/// Layout-compatible struct for {trait.Name} trait.");
            builder.AppendLine("/// Used for zero-copy field access via Unsafe.As.");
            builder.AppendLine("/// </summary>");
            builder.AppendLine("[global::System.Runtime.InteropServices.StructLayout(");
            builder.AppendLine("    global::System.Runtime.InteropServices.LayoutKind.Sequential)]");
            builder.AppendLine($"public struct {trait.LayoutStructName}");
            builder.OpenBrace();

            foreach (var prop in trait.Properties)
            {
                builder.AppendLine($"public {prop.TypeName} {prop.Name};");
            }

            builder.CloseBrace();
            builder.CloseBrace();

            return builder.ToString();
        }
    }
}
