using TraitEmulation.SourceGenerator.Models;
using TraitEmulation.SourceGenerator.Utilities;

namespace TraitEmulation.SourceGenerator.Generators
{
    internal static class TraitSpanFactoryGenerator
    {
        /// <summary>
        /// Generates span factory extension methods for a trait.
        /// Produces AsXxxSpan, AsXxxTraitSpan, AsXxxSpan2D, AsXxxTraitSpan2D methods.
        /// </summary>
        public static string Generate(TraitModel trait)
        {
            var builder = new CodeBuilder();
            var contractName = ConstraintInterfaceGenerator.GetContractName(trait);
            var shortName = trait.ShortName;
            var layoutType = $"{trait.EffectiveNamespace}.{trait.LayoutStructName}";

            builder.AppendLine("// <auto-generated/>");
            builder.AppendLine("#nullable enable");
            builder.AppendLine("using System;");
            builder.AppendLine("using System.Runtime.CompilerServices;");
            builder.AppendLine("using System.Runtime.InteropServices;");
            builder.AppendLine("using TraitEmulation.Runtime;");
            builder.AppendLine();
            builder.AppendLine($"namespace {trait.EffectiveNamespace}");
            builder.OpenBrace();

            builder.AppendLine("/// <summary>");
            builder.AppendLine($"/// Span factory extension methods for {trait.Name} trait.");
            builder.AppendLine("/// </summary>");
            builder.AppendLine($"public static class {trait.Name}SpanExtensions");
            builder.OpenBrace();

            // 1. AsXxxSpan - ReadOnly from ReadOnlySpan<T>
            builder.AppendLine("/// <summary>");
            builder.AppendLine($"/// Creates a read-only trait span viewing {trait.Name} fields across all elements.");
            builder.AppendLine("/// </summary>");
            builder.AppendLine("[MethodImpl(MethodImplOptions.AggressiveInlining)]");
            builder.AppendLine($"public static ReadOnlyTraitSpan<{layoutType}> As{shortName}Span<T>(");
            builder.AppendLine($"    this ReadOnlySpan<T> source)");
            builder.AppendLine($"    where T : unmanaged, {contractName}<T>");
            builder.OpenBrace();
            builder.AppendLine($"int offset = T.TraitOffset;");
            builder.AppendLine($"return new ReadOnlyTraitSpan<{layoutType}>(");
            builder.AppendLine("    ref Unsafe.AddByteOffset(");
            builder.AppendLine("        ref Unsafe.As<T, byte>(ref MemoryMarshal.GetReference(source)),");
            builder.AppendLine("        (nint)offset),");
            builder.AppendLine("    Unsafe.SizeOf<T>(),");
            builder.AppendLine("    source.Length);");
            builder.CloseBrace();
            builder.AppendLine();

            // 1b. AsXxxSpan - ReadOnly from Span<T> (so Span<T> users get ReadOnly without ambiguity)
            builder.AppendLine("/// <summary>");
            builder.AppendLine($"/// Creates a read-only trait span viewing {trait.Name} fields across all elements.");
            builder.AppendLine("/// </summary>");
            builder.AppendLine("[MethodImpl(MethodImplOptions.AggressiveInlining)]");
            builder.AppendLine($"public static ReadOnlyTraitSpan<{layoutType}> As{shortName}Span<T>(");
            builder.AppendLine($"    this Span<T> source)");
            builder.AppendLine($"    where T : unmanaged, {contractName}<T>");
            builder.OpenBrace();
            builder.AppendLine($"return As{shortName}Span<T>((ReadOnlySpan<T>)source);");
            builder.CloseBrace();
            builder.AppendLine();

            // 2. AsXxxTraitSpan - Mutable from Span<T>
            builder.AppendLine("/// <summary>");
            builder.AppendLine($"/// Creates a mutable trait span viewing {trait.Name} fields across all elements.");
            builder.AppendLine("/// </summary>");
            builder.AppendLine("[MethodImpl(MethodImplOptions.AggressiveInlining)]");
            builder.AppendLine($"public static TraitSpan<{layoutType}> As{shortName}TraitSpan<T>(");
            builder.AppendLine($"    this Span<T> source)");
            builder.AppendLine($"    where T : unmanaged, {contractName}<T>");
            builder.OpenBrace();
            builder.AppendLine($"int offset = T.TraitOffset;");
            builder.AppendLine($"return new TraitSpan<{layoutType}>(");
            builder.AppendLine("    ref Unsafe.AddByteOffset(");
            builder.AppendLine("        ref Unsafe.As<T, byte>(ref MemoryMarshal.GetReference(source)),");
            builder.AppendLine("        (nint)offset),");
            builder.AppendLine("    Unsafe.SizeOf<T>(),");
            builder.AppendLine("    source.Length);");
            builder.CloseBrace();
            builder.AppendLine();

            // 3. AsXxxSpan2D - ReadOnly 2D from ReadOnlySpan<T>
            builder.AppendLine("/// <summary>");
            builder.AppendLine($"/// Creates a 2D read-only trait span with the given dimensions.");
            builder.AppendLine("/// source.Length must equal width * height.");
            builder.AppendLine("/// </summary>");
            builder.AppendLine("[MethodImpl(MethodImplOptions.AggressiveInlining)]");
            builder.AppendLine($"public static ReadOnlyTraitSpan2D<{layoutType}> As{shortName}Span2D<T>(");
            builder.AppendLine($"    this ReadOnlySpan<T> source, int width, int height)");
            builder.AppendLine($"    where T : unmanaged, {contractName}<T>");
            builder.OpenBrace();
            builder.AppendLine("if (source.Length != width * height)");
            builder.AppendLine("    ThrowHelper.ThrowArgumentException_InvalidDimensions();");
            builder.AppendLine($"int offset = T.TraitOffset;");
            builder.AppendLine($"return new ReadOnlyTraitSpan2D<{layoutType}>(");
            builder.AppendLine("    ref Unsafe.AddByteOffset(");
            builder.AppendLine("        ref Unsafe.As<T, byte>(ref MemoryMarshal.GetReference(source)),");
            builder.AppendLine("        (nint)offset),");
            builder.AppendLine("    Unsafe.SizeOf<T>(),");
            builder.AppendLine("    width,");
            builder.AppendLine("    height);");
            builder.CloseBrace();
            builder.AppendLine();

            // 3b. AsXxxSpan2D - ReadOnly 2D from Span<T>
            builder.AppendLine("/// <summary>");
            builder.AppendLine($"/// Creates a 2D read-only trait span with the given dimensions.");
            builder.AppendLine("/// source.Length must equal width * height.");
            builder.AppendLine("/// </summary>");
            builder.AppendLine("[MethodImpl(MethodImplOptions.AggressiveInlining)]");
            builder.AppendLine($"public static ReadOnlyTraitSpan2D<{layoutType}> As{shortName}Span2D<T>(");
            builder.AppendLine($"    this Span<T> source, int width, int height)");
            builder.AppendLine($"    where T : unmanaged, {contractName}<T>");
            builder.OpenBrace();
            builder.AppendLine($"return As{shortName}Span2D<T>((ReadOnlySpan<T>)source, width, height);");
            builder.CloseBrace();
            builder.AppendLine();

            // 4. AsXxxTraitSpan2D - Mutable 2D from Span<T>
            builder.AppendLine("/// <summary>");
            builder.AppendLine($"/// Creates a 2D mutable trait span with the given dimensions.");
            builder.AppendLine("/// source.Length must equal width * height.");
            builder.AppendLine("/// </summary>");
            builder.AppendLine("[MethodImpl(MethodImplOptions.AggressiveInlining)]");
            builder.AppendLine($"public static TraitSpan2D<{layoutType}> As{shortName}TraitSpan2D<T>(");
            builder.AppendLine($"    this Span<T> source, int width, int height)");
            builder.AppendLine($"    where T : unmanaged, {contractName}<T>");
            builder.OpenBrace();
            builder.AppendLine("if (source.Length != width * height)");
            builder.AppendLine("    ThrowHelper.ThrowArgumentException_InvalidDimensions();");
            builder.AppendLine($"int offset = T.TraitOffset;");
            builder.AppendLine($"return new TraitSpan2D<{layoutType}>(");
            builder.AppendLine("    ref Unsafe.AddByteOffset(");
            builder.AppendLine("        ref Unsafe.As<T, byte>(ref MemoryMarshal.GetReference(source)),");
            builder.AppendLine("        (nint)offset),");
            builder.AppendLine("    Unsafe.SizeOf<T>(),");
            builder.AppendLine("    width,");
            builder.AppendLine("    height);");
            builder.CloseBrace();

            builder.CloseBrace();
            builder.CloseBrace();

            return builder.ToString();
        }
    }
}
